base_model: google/gemma-3-4b-it
model_type: AutoModelForCausalLM
trust_remote_code: true

# Quantization for memory efficiency
load_in_4bit: true
bnb_4bit_quant_type: nf4
bnb_4bit_use_double_quant: true
bnb_4bit_compute_dtype: bfloat16

# Gemma 3 specific
chat_template: gemma3
eot_tokens:
  - <end_of_turn>

datasets:
  - path: large-traversaal/urdu_datasets
    name: urdu_instruct
    type: chat_template
    field_messages: messages
    message_property_mappings:
      role: role
      content: content

dataset_prepared_path: prepared_data/urdu_gemma3
val_set_size: 0.01
output_dir: ./outputs/gemma3-4b-urdu

# LoRA settings
adapter: qlora
sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true

# Training settings - memory optimized
gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1

optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

bf16: auto
fp16: false
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

# Logging
logging_steps: 1
warmup_ratio: 0.1
weight_decay: 0.0

# Evaluation - skip initial eval to avoid issues
eval_strategy: steps
eval_steps: 100
saves_per_epoch: 1

# Weights & Biases
wandb_project: gemma-3-4b-urdu
wandb_entity: traversaal-research
wandb_watch:
wandb_name:
wandb_log_model:
