"""
Patch for transformers.modelcard compatibility
"""
import transformers

if not hasattr(transformers, 'modelcard'):
    class DummyModelCard:
        AUTOGENERATED_TRAINER_COMMENT = ""
    transformers.modelcard = DummyModelCard()
    print("✓ Patched transformers.modelcard")
else:
    print("✓ transformers.modelcard exists")
